# <u>NumPy Indexing and Selection.

In this lecture we will discuss how to select elements or groups of elements from an array.

In [2]:
import numpy as np

In [3]:
# Creating sample array

arr = np.arange(0,11)

In [4]:
# Show

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

---

# 1) Bracket Indexing and Selection.

The simplest way to pick one or some elements of an array looks very similar to python lists:

In [7]:
# Get a value at an index 8.

arr[8]

8

In [8]:
# Get values in a range

arr[1:5]

array([1, 2, 3, 4])

In [9]:
# Get values in a range

arr[0:5]

array([0, 1, 2, 3, 4])

In [10]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [11]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [12]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

---

# 2) Broadcasting.

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
# Setting a value with index range (Broadcasting).
arr[0:5] = 100

# Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [17]:
# Reset array, we'll see why I had to reset in  a moment.
arr = np.arange(0, 11)

# Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
# Important notes on Slices
slice_of_arr = arr[0:6]

# Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [19]:
slice_of_arr[0:]

array([0, 1, 2, 3, 4, 5])

In [20]:
# Change Slice
slice_of_arr[:] = 99

# Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [22]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! It's linked to the orignal array. NumPy does this to avoid memory problems for large arrays! The orignal array gets affected.

In [24]:
# To get a copy.
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [25]:
# Make changes to arr_copy.

arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [26]:
# arr remains same as we made a copy.

arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [27]:
# Broadcasting: If we take a slice of an array and assign diffrent values to that slice without explicitly making a copy of the orignal array,
# continued... it's going to affect the orignal array. In python lists this dosen't happen.

---

# 3) Indexing a 2D array (matrices).

The general format is **arr_2d[row][col]** or **arr_2d[row, col]**. I recommend usually using the comma notation for clarity.

In [30]:
arr_2d = np.array(([5,10,15],
                   [20,25,30],
                   [35,40,45]))

# Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [31]:
# Indexing row.

arr_2d[1]

array([20, 25, 30])

In [32]:
# Format is arr_2d[row][col] or arr_2d[row, col].

# Getting individual element value.

arr_2d[1][0]

20

In [33]:
# Getting individual element value
arr_2d[1, 0]

20

In [34]:
# 2D array slicing

# Shape (2,2) from top right corner(10, 15, 25, 30)

arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

- <u>NOTE:

    - :2 --> exclusive of 2

In [36]:
# Double brackets won't work for the above example, will give diffrent output.

arr_2d[:2][1:]

array([[20, 25, 30]])

In [37]:
# Shape bottom row.

arr_2d[2]

array([35, 40, 45])

In [38]:
# Shape bottom row (40, 45).

arr_2d[2, 1:]

array([40, 45])

---

# 4) Fancy Indexing

Fancy indexing allows us to select entire rows or columns out of order, to show this, let's quickly build out a numpy array: (only works for 2-D arrays that have same elements in a row.)

In [41]:
# Set up matrix

arr2d = np.zeros((10, 10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [42]:
# Shape(rows, columns)

arr2d.shape

(10, 10)

In [43]:
# Length of array

arr_length = arr2d.shape[1]
arr_length

10

In [44]:
arr2d[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [45]:
# Set up array

for i in range(arr_length): # range() here generates numbers from 0 to 9.
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following:

In [47]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [48]:
# Allows in any order

arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [49]:
# Allows in any order

arr2d[[4,2,7]]

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

### More Indexing Help

Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to find useful images, like this one:

<img src= 'http://memory.osu.edu/classes/python/_images/numpy_indexing.png' width=500/>

---

# 5) Conditional Selection.

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [53]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
# Compares every value in the array with the digit using the comparision operators.
# Comparing with a digit gives an array of bool values.

arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [55]:
# Save to a variable.

bool_arr = arr > 4

In [56]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [57]:
# Conditional Selection.
# Returns back only the values that happened to be True.

arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [58]:
# Conditional Selection.
# Doing it in a single step.
# Syntax notation that is going to be used more often throughout the course (in Pandas too).

arr[arr > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
arr[arr < 3]

array([1, 2])

In [60]:
x = 2
arr[arr > x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

---

In [61]:
# Practice example.

arr1 = np.arange(1, 51)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [62]:
arr1 = arr1.reshape(5, 10)
arr1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [63]:
# Grab 13, 14, 23 and 24.

arr1[1:3, 2:4]

array([[13, 14],
       [23, 24]])

---