# <u>NumPy Operations.

- Array with Array
- Array with Scalers
- Universal Array Functions

---

# <u>Arithmetic.

We can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [1]:
import numpy as np

arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Array with Array arithmetic operations.

In [11]:
# Adds matching element wise.

arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [13]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [91]:
# ZeroDivisionError: division by zero

# 1/0

In [93]:
# Warning on division by zero in NumPy, but not an error!
# Just replaced with nan (not a number).

arr / arr

C:\Users\user1\AppData\Local\Temp\ipykernel_16720\929013140.py:4: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [27]:
# Warning, not an error.

arr % arr

C:\Users\user1\AppData\Local\Temp\ipykernel_16720\1413099056.py:3: RuntimeWarning: divide by zero encountered in remainder
  arr % arr


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [52]:
arr ** arr

array([         1,          1,          4,         27,        256,
             3125,      46656,     823543,   16777216,  387420489,
       1410065408])

In [54]:
pow(arr, arr)

array([         1,          1,          4,         27,        256,
             3125,      46656,     823543,   16777216,  387420489,
       1410065408])

In [74]:
# TypeError: unsupported operand type(s) for ** or pow(): 'numpy.ndarray', 'numpy.ndarray', 'int'

# pow(arr, arr, arr)

### Array with Scalers arithmetic operations.

In [32]:
# Adds 100(scaler value) to every element in the array.

arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [34]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [38]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [42]:
arr / 100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])

In [46]:
# Warning.

100 / arr

C:\Users\user1\AppData\Local\Temp\ipykernel_16720\3305990774.py:3: RuntimeWarning: divide by zero encountered in divide
  100 / arr


array([         inf, 100.        ,  50.        ,  33.33333333,
        25.        ,  20.        ,  16.66666667,  14.28571429,
        12.5       ,  11.11111111,  10.        ])

In [48]:
# Also warning, but not an error instead infinity.

1 / arr

C:\Users\user1\AppData\Local\Temp\ipykernel_16720\2412344455.py:3: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [76]:
arr ** 3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [78]:
pow(arr, 3)

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [80]:
arr % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [86]:
# TypeError: unsupported operand type(s) for ** or pow(): 'numpy.ndarray', 'int', 'int'

# pow(arr, 3, 2)

In [3]:
arr ** 0.5

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

---

# <u>Universal Array Functions.

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [5]:
# Taking Square Roots

np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [7]:
# Calcualting exponential (e^).
# Euler’s number (denoted as e, approximately 2.718).
# Example: np.exp(x) means e^x, Where: e ≈ 2.71828 and x is each element in the input array.

np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [9]:
np.max(arr) #same as arr.max()

10

In [15]:
np.sin(arr) # Note that arr is taken as radian.

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [19]:
np.log(arr) # log base e / natural logarith.

C:\Users\user1\AppData\Local\Temp\ipykernel_17204\2790065801.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr) # log base e / natural logarith.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

---